import {
  AUD_TOKEN_CODE,
  AUD_TOKEN_ID,
  AUD_TOKEN_NAME,
  CAD_TOKEN_CODE,
  CAD_TOKEN_ID,
  CAD_TOKEN_NAME,
  CHF_TOKEN_CODE,
  CHF_TOKEN_ID,
  CHF_TOKEN_NAME,
  GBP_TOKEN_CODE,
  GBP_TOKEN_ID,
  GBP_TOKEN_NAME,
  JPY_TOKEN_CODE,
  JPY_TOKEN_ID,
  JPY_TOKEN_NAME,
  SGD_TOKEN_CODE,
  SGD_TOKEN_ID,
  SGD_TOKEN_NAME,
  USD_TOKEN_CODE,
  USD_TOKEN_ID,
  USD_TOKEN_NAME,
  VND_TOKEN_CODE,
  VND_TOKEN_ID,
  VND_TOKEN_NAME,
} from '../configs';
import { Currency } from '../controllers/forex/types';

export const currencies: Currency[] = [
  {
    symbol: '$',
    code: 'AUD',
    name: 'Australian Dollar',
    tokenId: AUD_TOKEN_ID,
    tokenCode: AUD_TOKEN_CODE,
    tokenName: AUD_TOKEN_NAME,
    exponent: 2,
  },
  {
    symbol: '$',
    code: 'CAD',
    name: 'Canadian Dollar',
    tokenId: CAD_TOKEN_ID,
    tokenCode: CAD_TOKEN_CODE,
    tokenName: CAD_TOKEN_NAME,
    exponent: 2,
  },
  {
    symbol: 'Fr',
    code: 'CHF',
    name: 'Swiss Franc',
    tokenId: CHF_TOKEN_ID,
    tokenCode: CHF_TOKEN_CODE,
    tokenName: CHF_TOKEN_NAME,
    exponent: 2,
  },
  {
    symbol: '€',
    code: 'EUR',
    name: 'Euro',
    tokenId: GBP_TOKEN_ID,
    tokenCode: GBP_TOKEN_CODE,
    tokenName: GBP_TOKEN_NAME,
    exponent: 2,
  },
  {
    symbol: '£',
    code: 'GBP',
    name: 'British Pound',
    tokenId: GBP_TOKEN_ID,
    tokenCode: GBP_TOKEN_CODE,
    tokenName: GBP_TOKEN_NAME,
    exponent: 2,
  },
  {
    symbol: '¥',
    code: 'JPY',
    name: 'Japanese Yen',
    tokenId: JPY_TOKEN_ID,
    tokenCode: JPY_TOKEN_CODE,
    tokenName: JPY_TOKEN_NAME,
    exponent: 0,
  },
  {
    symbol: '$',
    code: 'SGD',
    name: 'Singapore Dollar',
    tokenId: SGD_TOKEN_ID,
    tokenCode: SGD_TOKEN_CODE,
    tokenName: SGD_TOKEN_NAME,
    exponent: 2,
  },
  {
    symbol: '$',
    code: 'USD',
    name: 'United States Dollar',
    tokenId: USD_TOKEN_ID,
    tokenCode: USD_TOKEN_CODE,
    tokenName: USD_TOKEN_NAME,
    exponent: 2,
  },
  {
    symbol: 'đ',
    code: 'VND',
    name: 'Vietnamese Dong',
    tokenId: VND_TOKEN_ID,
    tokenCode: VND_TOKEN_CODE,
    tokenName: VND_TOKEN_NAME,
    exponent: 0,
  },
];
